name: Unzip and Commit

on:
  workflow_dispatch:  # Manual trigger
  push:               # Optional: triggers on any push

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unzip the file
      run: unzip frontend.zip -d unzipped_folder

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GH_PAT }}  # this must be from Secrets, not Variables
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add unzipped_folder
        git commit -m "Unzipped and committed contents of frontend.zip" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref_name }}
