name: Unzip and Commit

on:
  workflow_dispatch:
  push:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Commit and push changes to feature branch
      env:
        TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git checkout -b feature/unzipped-frontend
        git add unzipped_folder
        git commit -m "Unzipped frontend.zip" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push -u origin feature/unzipped-frontend

