name: Unzip and Commit

on:
  workflow_dispatch:
  push:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if frontend.zip exists
      run: |
        if [ ! -f frontend.zip ]; then
          echo "frontend.zip not found"
          exit 1
        fi

    - name: Unzip the file
      run: unzip frontend.zip -d unzipped_folder

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add unzipped_folder
        git commit -m "Unzipped frontend.zip on $(date)" || echo "No changes to commit"
        git push origin HEAD:"${{ github.ref_name }}"
