name: Unzip File

on:
  workflow_dispatch:  # Manual trigger via GitHub Actions UI
  push:               # Or trigger on push

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unzip the file
      run: unzip yourfile.zip -d unzipped_folder

    - name: Commit unzipped content
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add unzipped_folder
        git commit -m "Unzipped yourfile.zip"
        git push
